# Generated by Django 3.2 on 2021-05-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_activity', '0003_auto_20210526_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='post_image',
            field=models.FileField(blank=True, upload_to='post_pic'),
        ),
    ]
