# Generated by Django 3.2 on 2021-05-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user_activity', '0004_alter_userpost_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ['-created_date']},
        ),
    ]
