# Generated by Django 3.2 on 2021-05-01 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='profile_pics', verbose_name='Profile Photo')),
                ('school', models.CharField(blank=True, max_length=150, verbose_name='Add School')),
                ('College', models.CharField(blank=True, max_length=150, verbose_name='Add College')),
                ('other_institution', models.CharField(blank=True, max_length=250, verbose_name='Add institution')),
                ('training', models.CharField(blank=True, max_length=250, verbose_name='Add training(if you have any)')),
                ('dob', models.DateField(blank=True, verbose_name='Date of Birth')),
                ('facebook_id', models.URLField(blank=True, verbose_name='Facebok Id')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_description', models.TextField(blank=True)),
                ('post_image', models.FileField(blank=True, upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_images', models.FileField(upload_to='')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_post_and_image', to='app_login.userpost')),
            ],
        ),
    ]
